version: '3.7'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'