server:
  port: 8081

external:
  api:
    url: https://jsonplaceholder.typicode.com

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true
  flyway:
    locations: classpath:/db/migration/postgres

keycloak:
  server-url: http://localhost:8080/
  realm: course-bay
  client-id: spring
  client-secret: qIMsIVfQLG9Y2DA8izbrlWZDSI3SRVKg

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR

