external:
  api:
    url: http://localhost:8081/

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: secret
    driver-class-name: org.h2.Driver
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect
        hibernate.format_sql: true
    show-sql: false
  flyway:
    locations: classpath:db/migration/h2

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR