external:
  api:
    url: https://jsonplaceholder.typicode.com

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true
  flyway:
    locations: classpath:/db/migration/postgres

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR
